name: benchmark
on:
  push:
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - 'website/**'

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Required Libraries
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev

      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 20
          packageManager: yarn

      - name: Build Packages
        run: yarn build

      - name: Setup K6
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6=0.37.0

      - name: Start Benchmark
        working-directory: ./benchmark
        run: |
          yarn test
        env:
          NODE_NO_WARNINGS: true
          NODE_ENV: production
          GITHUB_PR: ${{ github.event.number }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  node-fetch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - noConsumeBody
          - consumeBody
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 20
          packageManager: yarn
      - name: Start httpbin
        run: yarn workspace @benchmarks/node-fetch run start:httpbin &
      - name: Start server
        run: yarn workspace @benchmarks/node-fetch run start:server &
      - name: Benchmark
        uses: grafana/k6-action@v0.3.1
        env:
          SCENARIO: ${{ matrix.scenario }}
        with:
          filename: ./benchmarks/node-fetch/k6.js
