name: Sync labels
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
        with:
          manifest: .github/labels.yml
          prune: false
