name: pr

on:
  pull_request:
    branches:
      - master

jobs:
  dependencies:
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yaml@main
    if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  alpha:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    if:
      ${{ (github.event.pull_request.head.repo.full_name == github.repository ||
      github.event.inputs.onDemand == 'yes') && github.event.pull_request.title != 'Upcoming Release
      Changes' }}
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@main
    with:
      npmTag: alpha
      buildScript: build
      nodeVersion: 22
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}

  release-candidate:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    if:
      ${{ github.event.pull_request.head.repo.full_name == github.repository &&
      github.event.pull_request.title == 'Upcoming Release Changes' }}
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@main
    with:
      npmTag: rc
      buildScript: build
      nodeVersion: 22
      restoreDeletedChangesets: true
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}
