name: Tests

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  prettier-check:
    name: 🧹 Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 17
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-17-yarn-${{hashFiles('yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-17-yarn
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Prettier Check
        run: yarn prettier:check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 17
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-17-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-17-yarn
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Lint
        run: yarn lint
  build:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 17
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-17-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-17-yarn
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Type Check
        run: yarn ts:check
  test:
    name: Unit Test on Node ${{matrix.node-version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 17]
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{matrix.node-version}}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.node-version}}-yarn

      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Cache Jest
        uses: actions/cache@v2
        with:
          path: .cache/jest
          key: ${{ runner.os }}-${{matrix.node-version}}-jest-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.node-version}}-jest-
      - name: Test
        run: yarn test --ci
        env:
          CI: true
  test_esm:
    name: ESM Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 17
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-17-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-17-yarn
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Build Packages
        run: yarn build
      - name: Test ESM
        run: node scripts/test-esm.mjs
