name: test

on:
  push:
    branches:
      - master
  pull_request: {}

env:
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  prettier-check:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
      - name: Install Required Libraries
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev
      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 22
      - name: Prettier Check
        run: yarn prettier:check
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
      - name: Install Required Libraries
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev
      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 22
      - name: ESLint
        run: yarn lint

  type-check:
    name: type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
      - name: Install Required Libraries
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev
      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 22
      - name: Type Check
        run: yarn ts:check

  unit:
    name: unit / node ${{matrix.node-version}}
    runs-on: ubuntu-latest
    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 8888:80
    strategy:
      matrix:
        node-version: [18, 20, 22]
      fail-fast: false
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
      - name: Install Required Libraries
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev
      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: ${{ matrix.node-version }}
      - name: Cache Jest
        uses: actions/cache@v4
        with:
          path: .cache/jest
          key: ${{ runner.os }}-${{matrix.node-version}}-jest-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.node-version}}-jest-
      - name: Test
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: yarn test --ci

  unit-leaks:
    name: unit / leaks / node ${{matrix.node-version}}
    runs-on: ubuntu-latest
    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 8888:80
    strategy:
      matrix:
        node-version: [18, 20, 22]
      fail-fast: false
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
      - name: Install Required Libraries
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev
      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: ${{ matrix.node-version }}
      - name: Cache Jest
        uses: actions/cache@v4
        with:
          path: .cache/jest
          key: ${{ runner.os }}-${{matrix.node-version}}-jest-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.node-version}}-jest-
      - name: Test
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: yarn test:leaks --ci

  esm:
    name: esm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
      - name: Install Required Libraries
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev
      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 22
      - name: Build Packages
        run: yarn build
      - name: Test ESM
        run: yarn esm:check
